- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Netstat
      command: netstat -rn
      register: outputroute
      
    - name: Print it
      debug: 
        msg: "{{ outputroute }}"

    - name: Ping
      command: ping 192.168.50.169 -c 5
      register: outputroute
      
    - name: Print it
      debug: 
        msg: "{{ outputroute }}"
