- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Netstat
      command: netstat -rn
      register: output
    - debug: output
